name: Build

on:
  push:
    branches: [ "main", "develop", "release/**" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
      versionCode: ${{ steps.run_number.outputs.versionCode }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.6
        with:
          versionSpec: '5.x'
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.6
        with:
          useConfigFile: true
          configFilePath: ./gitversion.yml
      - name: Display SemVer
        run: |
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
  build:
    strategy:
      matrix:
        module: ["compose", "activity"]
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: -Pversion=${{ steps.gitversion.outputs.semVer }} ${{ matrix.module }}:build
      - name: Rename AAR
        run: mv ./${{ matrix.module }}/build/outputs/aar/${{ matrix.module }}-release.aar ./${{ matrix.module }}.aar
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.module }}-aar
          path: ./${{ matrix.module }}.aar
  release:
    needs:
      - version
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.version.outputs.version }}
          release_name: cloud-${{ needs.version.outputs.version }}
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/main' }}
  upload-to-release:
    strategy:
      matrix:
        module: [ "compose", "activity" ]
    needs:
      - release
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: ${{ matrix.module }}-aar
          path: ./
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./${{ matrix.module }}.aar
          asset_name: ${{ matrix.module }}.aar
          asset_content_type: application/zip
  publish-package:
    strategy:
      matrix:
        module: [ "compose", "activity" ]
    needs:
      - version
      - build
    if: ${{ always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release')) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - uses: actions/download-artifact@master
        with:
          name: ${{ matrix.module }}-aar
          path: ./
      - name: Rename AAR
        run: mv ./${{ matrix.module }}.aar ./${{ matrix.module }}/build/outputs/aar/${{ matrix.module }}-release.aar
      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: -Pversion=${{ needs.version.outputs.version }} ${{ matrix.module }}:publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
